{ pkgs, config, ... }:

{

  # Development packages
  packages = with pkgs; [
    # Node.js & package management
    nodejs_20
    corepack

    # Python (for python-sdk)
    python311
    poetry

    # Docker (for local-ses-sns)
    docker
    docker-compose

    # Deployment tools
    railway

    # Development utilities
    git
    jq
    curl
    openssl

    # AWS CLI (for SES/SNS testing)
    awscli2

    # Secrets management
    secretspec
  ];

  # PostgreSQL service
  services.postgres = {
    enable = true;
    package = pkgs.postgresql_16;
    listen_addresses = "127.0.0.1";
    port = 54320;
    initialDatabases = [{
      name = "usesend";
      user = "usesend";
      pass = "password";
    }];
    initialScript = ''
      DO $$
      BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'usesend') THEN
          CREATE ROLE usesend WITH LOGIN PASSWORD 'password' SUPERUSER CREATEDB;
        ELSE
          ALTER ROLE usesend WITH SUPERUSER CREATEDB;
        END IF;
      END
      $$;
    '';
  };

  # Redis service
  services.redis = {
    enable = true;
    port = 6379;
  };

  # MinIO for S3-compatible storage
  services.minio = {
    enable = true;
    accessKey = "unsend";
    secretKey = "password";
    buckets = [ "unsend" ];
    listenAddress = "127.0.0.1:9002";
    consoleAddress = "127.0.0.1:9001";
  };

  # Environment variables
  env = {
    # Database
    DATABASE_URL = "postgresql://usesend:password@127.0.0.1:54320/usesend";

    # Redis
    REDIS_URL = "redis://127.0.0.1:6379";

    # NextAuth
    NEXTAUTH_URL = "http://localhost:3000";
    NEXTAUTH_SECRET = "dev-secret-change-in-production";

    # SMTP (defaults for dev)
    SMTP_HOST = "smtp.usesend.com";
    SMTP_PORT = "465";
    SMTP_USER = "usesend";

    # AWS/SES - point to local mock
    AWS_DEFAULT_REGION = "us-east-1";
    AWS_ACCESS_KEY = "dev-access-key";
    AWS_SECRET_KEY = "dev-secret-key";
    AWS_SES_ENDPOINT = "http://localhost:5350/api/ses";
    AWS_SNS_ENDPOINT = "http://localhost:5350/api/sns";

    # S3/MinIO
    S3_COMPATIBLE_ACCESS_KEY = "unsend";
    S3_COMPATIBLE_SECRET_KEY = "password";
    S3_COMPATIBLE_API_URL = "http://localhost:9002";
    S3_COMPATIBLE_PUBLIC_URL = "http://localhost:9002";
    S3_COMPATIBLE_BUCKET = "unsend";

    # App settings
    FROM_EMAIL = "hello@localhost";
    API_RATE_LIMIT = "100";
    AUTH_EMAIL_RATE_LIMIT = "10";
    NEXT_PUBLIC_IS_CLOUD = "false";

  };

  # Process management - run local-ses-sns via docker
  processes = {
    local-ses-sns.exec = ''
      docker run --rm \
        -p 5350:3000 \
        -e WEBHOOK_URL=http://host.docker.internal:3000/api/ses_callback \
        --add-host=host.docker.internal:host-gateway \
        unsend/local-ses-sns:latest
    '';
  };

  enterShell = ''
    # Generate .env file for tools that don't inherit shell env vars
    cat > .env << 'EOF'
# Auto-generated by devenv - do not commit
DATABASE_URL=postgresql://usesend:password@127.0.0.1:54320/usesend
REDIS_URL=redis://127.0.0.1:6379
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=dev-secret-change-in-production
SMTP_HOST=smtp.usesend.com
SMTP_PORT=465
SMTP_USER=usesend
AWS_DEFAULT_REGION=us-east-1
AWS_ACCESS_KEY=dev-access-key
AWS_SECRET_KEY=dev-secret-key
AWS_SES_ENDPOINT=http://localhost:5350/api/ses
AWS_SNS_ENDPOINT=http://localhost:5350/api/sns
S3_COMPATIBLE_ACCESS_KEY=unsend
S3_COMPATIBLE_SECRET_KEY=password
S3_COMPATIBLE_API_URL=http://localhost:9002
S3_COMPATIBLE_PUBLIC_URL=http://localhost:9002
S3_COMPATIBLE_BUCKET=unsend
FROM_EMAIL=hello@localhost
API_RATE_LIMIT=100
AUTH_EMAIL_RATE_LIMIT=10
NEXT_PUBLIC_IS_CLOUD=false
EOF

    # Append secrets from secretspec to .env
    if command -v secretspec &> /dev/null; then
      # Use secretspec run with env to capture injected vars, filter for GITHUB_*
      secretspec run --profile development -- env 2>/dev/null | grep -E '^GITHUB_' >> .env || true
    fi

    # Also copy to apps/web for Next.js
    cp .env apps/web/.env

    echo ""
    echo "=========================================="
    echo "  usesend development environment"
    echo "=========================================="
    echo ""
    echo "Services (run 'devenv up' to start):"
    echo "  PostgreSQL: 127.0.0.1:54320 (user: usesend, db: usesend)"
    echo "  Redis:      127.0.0.1:6379"
    echo "  MinIO:      127.0.0.1:9002 (console: 9001)"
    echo "  SES/SNS:    127.0.0.1:5350 (via Docker)"
    echo ""
    echo ".env file generated with dev configuration."
    echo ""
    echo "Commands:"
    echo "  devenv up         - Start all services"
    echo "  devenv up -d      - Start services in background"
    echo "  pnpm install      - Install dependencies"
    echo "  pnpm dev          - Start Next.js dev server"
    echo "  pnpm db:migrate-dev - Run database migrations"
    echo "  pnpm db:studio    - Open Prisma Studio"
    echo ""
    echo "Node: $(node --version)"
    echo ""
  '';

}
