[project]
name = "usesend"
revision = "1.0"
default_profile = "development"

[profiles.development]
GITHUB_ID = { description = "GitHub OAuth client ID" }
GITHUB_SECRET = { description = "GitHub OAuth client secret" }
